name: smart_parent_assistant
description: AI powered baby cry analysis app

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  provider: ^6.1.2
  tflite_flutter: ^0.10.4
  supabase_flutter: ^2.5.6
  image_picker: ^1.1.2
  google_fonts: ^6.2.1

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/ml/